### ISSUE TITLE
Likely bug in Request.Validate() - any request with an ID will *only* validate the ID

### ISSUE THREAD

**Issue by ezzatron** [dogmatiq/harpy#13]
Relevant code: https://github.com/dogmatiq/harpy/blob/b8df01b455faf5300cf6ef5ab8334f07e16fe113/request.go#L81-L83

**Comment by ezzatron** [comment]
I imagine the way that this slipped through tests was that each test request omitted the ID in order to be as simple an example as possible.

**Comment by jmalloc** [comment]
Note to self: also check for `len(r.ID) == 0`, not _just_ `nil`.
